"""initial migration

Revision ID: 2e3bf49d9e33
Revises: 
Create Date: 2026-03-24 22:22:03.805533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3bf49d9e33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temperature_morning', sa.Float(), nullable=False),
    sa.Column('temperature_afternoon', sa.Float(), nullable=False),
    sa.Column('temperature_night', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_column('weather')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('weather', sa.VARCHAR(length=100), nullable=False))

    op.drop_table('temperature')
    # ### end Alembic commands ###
